homeassistant:
  customize:
    light.yeelight_rgb_34ce008228f2:
      friendly_name: "Schlafzimmer Deckenlampe"
      emulated_hue_name: "Schlafzimmer Deckenlampe"

group:
  bedroom:
    name: "Schlafzimmer"
    icon: mdi:hotel
    view: no
    entities:
      - light.yeelight_rgb_34ce008228f2
